-- Criar a tabela de produtos
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  platform TEXT NOT NULL,
  category TEXT NOT NULL,
  price_original INTEGER NOT NULL, -- valor em centavos
  price_promo INTEGER NOT NULL, -- valor em centavos
  discount_pct INTEGER NOT NULL,
  affiliate_url TEXT NOT NULL,
  clicks INTEGER DEFAULT 0 NOT NULL,
  active BOOLEAN DEFAULT true NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Política para leitura pública (Qualquer um pode ver os produtos ativos)
CREATE POLICY "Produtos ativos são visíveis para todos"
ON public.products FOR SELECT
USING (active = true);

-- Política para leitura restrita (Admin pode ver inativos e fazer tudo)
-- Assume que apenas usuários autenticados via Supabase Auth são os donos
CREATE POLICY "Usuários autenticados podem gerenciar produtos"
ON public.products FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');
